//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Accounting_EL
    {
        public System.DateTime Report_Date { get; set; }
        public System.DateTime Processing_Date { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Portfolio { get; set; }
        public double Accounting_EL { get; set; }
        public string Product_Code { get; set; }
        public string Reference_Nbr { get; set; }
        public string Impairment_Stage { get; set; }
        public int Version { get; set; }
        public string IAS39_CATEGORY { get; set; }
        public int Grade_Adjust { get; set; }
        public string Portfolio_Name { get; set; }
        public int Low_Grade { get; set; }
        public int High_Grade { get; set; }
        public string Risk_Level { get; set; }
    }
}
