//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_ISIN_Changed_IntRevise
    {
        public string Bond_Number_Old { get; set; }
        public string Portfolio_Name_Old { get; set; }
        public double Interest_Receivable { get; set; }
        public double Interest_Receivable_Tw { get; set; }
        public System.DateTime Report_Date { get; set; }
        public System.DateTime Processing_Date { get; set; }
        public int Version { get; set; }
        public string Bond_Number_New { get; set; }
        public string Lots_New { get; set; }
        public string Portfolio_Name_New { get; set; }
        public Nullable<double> Ori_Amount_New { get; set; }
        public string CreateUser { get; set; }
        public string Lots_Old { get; set; }
    }
}
