//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Qualitative_Assessment
    {
        public string Reference_Nbr { get; set; }
        public int Version { get; set; }
        public System.DateTime Report_Date { get; set; }
        public string Assessment_Kind { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public int Assessment_Result_Version { get; set; }
        public string Assessment_Result { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Portfolio { get; set; }
        public Nullable<System.DateTime> Origination_Date { get; set; }
        public string Portfolio_Name { get; set; }
        public string Auditor_Reply { get; set; }
        public string Auditor_Return { get; set; }
        public string Send_to_Auditor { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public string Assessor { get; set; }
        public Nullable<System.DateTime> Assessment_date { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Audit_date { get; set; }
        public Nullable<int> Result_Version_Confirm { get; set; }
        public string Quantitative_Pass_Confirm { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
        public string Extra_Case { get; set; }
    }
}
