//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Basic_Assessment
    {
        public string Reference_Nbr { get; set; }
        public int Version { get; set; }
        public System.DateTime Report_Date { get; set; }
        public System.DateTime Processing_Date { get; set; }
        public string Bond_Type { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public string Lien_position { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Portfolio { get; set; }
        public string Portfolio_Name { get; set; }
        public Nullable<System.DateTime> Origination_Date { get; set; }
        public Nullable<int> Original_External_Rating { get; set; }
        public Nullable<int> Current_External_Rating { get; set; }
        public string Rating_Ori_Good_IND { get; set; }
        public string Rating_Curr_Good_Ind { get; set; }
        public Nullable<int> Curr_Ori_Rating_Diff { get; set; }
        public string Basic_Pass { get; set; }
        public Nullable<int> Map_Rule_Id_D69 { get; set; }
        public Nullable<double> Cost_Value { get; set; }
        public Nullable<double> Market_Value_Ori { get; set; }
        public Nullable<double> Value_Change_Ratio { get; set; }
        public string Value_Change_Ratio_Pass { get; set; }
        public Nullable<int> Accumulation_Loss_last_Month { get; set; }
        public Nullable<int> Accumulation_Loss_This_Month { get; set; }
        public string Watch_IND { get; set; }
        public string Map_Rule_Id_D70 { get; set; }
        public string Warning_IND { get; set; }
        public string Map_Rule_Id_D71 { get; set; }
        public Nullable<double> Chg_In_Spread { get; set; }
        public string Spread_Change_Over { get; set; }
        public Nullable<int> Chg_In_Spread_last_Month { get; set; }
        public Nullable<int> Chg_In_Spread_This_Month { get; set; }
        public string Watch_IND_Override { get; set; }
        public string Watch_IND_Override_Desc { get; set; }
        public Nullable<System.DateTime> Watch_IND_Override_Date { get; set; }
        public string Watch_IND_Override_User { get; set; }
        public string Warning_IND_Override { get; set; }
        public string Warning_IND_Override_DESC { get; set; }
        public Nullable<System.DateTime> Warning_IND_Override_Date { get; set; }
        public string Warning_IND_Override_User { get; set; }
    }
}
