//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Account_AssessmentCheck
    {
        public int Id { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Portfolio_Name { get; set; }
        public string Portfolio { get; set; }
        public Nullable<System.DateTime> Maturity_Date { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<System.DateTime> Report_Date { get; set; }
        public Nullable<double> Amort_Amt_import { get; set; }
        public Nullable<double> Amort_Amt_import_TW { get; set; }
        public Nullable<double> Interest_Receivable_import { get; set; }
        public Nullable<double> Interest_Receivable_import_TW { get; set; }
        public Nullable<double> PD_Interest_Receivable_import { get; set; }
        public Nullable<double> PD_Amort_import { get; set; }
        public Nullable<double> LGD_Amort_import { get; set; }
        public Nullable<double> LGD_Interest_Receivable_import { get; set; }
        public Nullable<double> Lifetime_EL_Import { get; set; }
        public Nullable<double> Y1_EL_Import { get; set; }
        public Nullable<double> EL_import_Principle { get; set; }
        public Nullable<double> EL_import_Int { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
    }
}
