//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Account_Info
    {
        public string Reference_Nbr { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Segment_Name { get; set; }
        public string CURR_SP_Issuer { get; set; }
        public string CURR_Moodys_Issuer { get; set; }
        public string CURR_Fitch_Issuer { get; set; }
        public string CURR_TW_Issuer { get; set; }
        public string CURR_SP_Issue { get; set; }
        public string CURR_Moodys_Issue { get; set; }
        public string CURR_Fitch_Issue { get; set; }
        public string CURR_TW_Issue { get; set; }
        public Nullable<double> Ori_Amount { get; set; }
        public Nullable<double> Current_Int_Rate { get; set; }
        public Nullable<System.DateTime> Origination_Date { get; set; }
        public Nullable<System.DateTime> Maturity_Date { get; set; }
        public string Principal_Payment_Method_Code { get; set; }
        public string Payment_Frequency { get; set; }
        public string Baloon_Freq { get; set; }
        public string ISSUER_AREA { get; set; }
        public string Industry_Sector { get; set; }
        public string PRODUCT { get; set; }
        public string IAS39_CATEGORY { get; set; }
        public Nullable<double> Principal { get; set; }
        public Nullable<double> Amort_Amt_Tw { get; set; }
        public Nullable<double> Interest_Receivable { get; set; }
        public Nullable<double> Interest_Receivable_Tw { get; set; }
        public string Interest_Rate_Type { get; set; }
        public string IMPAIR_YN { get; set; }
        public Nullable<double> EIR { get; set; }
        public string Currency_Code { get; set; }
        public Nullable<System.DateTime> Report_Date { get; set; }
        public string ISSUER { get; set; }
        public string Country_Risk { get; set; }
        public Nullable<double> Ex_rate { get; set; }
        public string Lien_position { get; set; }
        public string Portfolio { get; set; }
        public string ASSET_SEG { get; set; }
        public Nullable<double> Ori_Ex_rate { get; set; }
        public string Bond_Type { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public Nullable<System.DateTime> Processing_Date { get; set; }
        public Nullable<int> Version { get; set; }
        public string Bond_Aera { get; set; }
        public string Asset_Type { get; set; }
        public string IH_OS { get; set; }
        public Nullable<double> Amount_TW_Ori_Ex_rate { get; set; }
        public Nullable<double> Amort_Amt_Ori_Tw { get; set; }
        public Nullable<double> Market_Value_Ori { get; set; }
        public Nullable<double> Market_Value_TW { get; set; }
        public Nullable<System.DateTime> Value_date { get; set; }
        public string Portfolio_Name { get; set; }
        public string ISIN_Changed_Ind { get; set; }
        public string Bond_Number_Old { get; set; }
        public string Lots_Old { get; set; }
        public string Portfolio_Name_Old { get; set; }
        public string Security_Name { get; set; }
        public Nullable<System.DateTime> Origination_Date_Old { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
        public string Assessment_Check { get; set; }
    }
}
