//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Category_Info
    {
        public string Memo { get; set; }
        public string Bloomberg_Ticker { get; set; }
        public string Bond_Type { get; set; }
        public string Corp_NonCorp { get; set; }
        public string Sector_External { get; set; }
        public string Sector_Internal { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public string Sector_Research { get; set; }
        public string Sector_Extra { get; set; }
        public System.DateTime Processing_Date { get; set; }
    }
}
