//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Quantitative_Resource
    {
        public string Reference_Nbr { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Segment_Name { get; set; }
        public int Version { get; set; }
        public System.DateTime Report_Date { get; set; }
        public Nullable<System.DateTime> Processing_Date { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public Nullable<double> Net_Debt { get; set; }
        public Nullable<double> Total_Asset { get; set; }
        public Nullable<double> CFO { get; set; }
        public Nullable<double> Int_Expense { get; set; }
        public Nullable<double> CET1_Capital_Ratio { get; set; }
        public Nullable<double> Lerverage_Ratio { get; set; }
        public Nullable<double> Liquiduty_Coverage_Ratio { get; set; }
        public Nullable<double> Total_Equity { get; set; }
        public Nullable<double> BS_TOT_ASSET { get; set; }
        public Nullable<double> RBC_Ratio { get; set; }
        public Nullable<double> MCCSR_Ratio { get; set; }
        public Nullable<double> Solvency_II_Ratio { get; set; }
        public Nullable<double> SHORT_AND_LONG_TERM_DEBT { get; set; }
        public Nullable<double> Cash_and_Cash_Equivalents { get; set; }
        public Nullable<double> Short_Term_Debt { get; set; }
        public string ISSUER_AREA { get; set; }
        public Nullable<double> IGS_INDEX { get; set; }
        public Nullable<double> IGS_INDEX_Increase { get; set; }
        public Nullable<double> External_Debt_Rate { get; set; }
        public Nullable<double> FC_Indexed_Debt_Rate { get; set; }
        public Nullable<double> CEIC_Value { get; set; }
        public Nullable<double> Short_term_Debt_Ratio { get; set; }
        public Nullable<double> GDP_Yearly_Avg { get; set; }
        public Nullable<double> Quantitative_CLO_1 { get; set; }
        public Nullable<double> Quantitative_CLO_2 { get; set; }
        public Nullable<double> Quantitative_CLO_2_Threshold { get; set; }
        public Nullable<double> Quantitative_CLO_3 { get; set; }
        public Nullable<double> Quantitative_CLO_3_Threshold { get; set; }
        public Nullable<double> Quantitative_CLO_4 { get; set; }
        public Nullable<double> Quantitative_CLO_4_Threshold { get; set; }
        public string Portfolio { get; set; }
        public Nullable<System.DateTime> Origination_Date { get; set; }
        public string Portfolio_Name { get; set; }
        public int Assessment_Result_Version { get; set; }
        public string Auditor_Reply { get; set; }
        public string Auditor_Return { get; set; }
        public string Send_to_Auditor { get; set; }
        public Nullable<System.DateTime> Send_Time { get; set; }
        public string Assessor { get; set; }
        public Nullable<System.DateTime> Assessment_date { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Audit_date { get; set; }
        public Nullable<int> Result_Version_Confirm { get; set; }
        public string Quantitative_Pass_Confirm { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    }
}
