//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bond_Ticker_Info
    {
        public System.DateTime Report_Date { get; set; }
        public int Version { get; set; }
        public string Bond_Number { get; set; }
        public string Lots { get; set; }
        public string Portfolio_Name { get; set; }
        public string PRODUCT { get; set; }
        public string Lien_position { get; set; }
        public string Security_Ticker { get; set; }
        public string Security_Des { get; set; }
        public string Bloomberg_Ticker { get; set; }
        public string Bond_Type { get; set; }
        public string Assessment_Sub_Kind { get; set; }
        public Nullable<System.DateTime> Processing_Date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    }
}
