//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Econ_F_YYYYMMDD
    {
        public string Processing_Date { get; set; }
        public string Product_Code { get; set; }
        public string Data_ID { get; set; }
        public string Year_Quartly { get; set; }
        public Nullable<double> PD_Quartly { get; set; }
        public Nullable<double> CPI_INDX_Index { get; set; }
        public Nullable<double> CACPSA_Index { get; set; }
        public Nullable<double> KOCPI_Index { get; set; }
        public Nullable<double> EACPI_Index { get; set; }
        public Nullable<double> GRCP2000_Index { get; set; }
        public Nullable<double> UKRPCHVJ_Index { get; set; }
        public Nullable<double> NECPIND_Index { get; set; }
        public Nullable<double> AUCCTOTS_Index { get; set; }
        public Nullable<double> JCPTSGEN_Index { get; set; }
        public Nullable<double> USGG3M_Index { get; set; }
        public Nullable<double> GECU3M_Index { get; set; }
        public Nullable<double> USGG10YR_Index { get; set; }
        public Nullable<double> GECU10YR_Index { get; set; }
        public Nullable<double> DEBPTOTL_Index { get; set; }
        public Nullable<double> NKY_Index { get; set; }
        public Nullable<double> INDU_Index { get; set; }
        public Nullable<double> CCMP_Index { get; set; }
        public Nullable<double> SPX_Index { get; set; }
        public Nullable<double> DAX_Index { get; set; }
        public Nullable<double> DJST_Index { get; set; }
        public Nullable<double> USURTOT_Index { get; set; }
        public Nullable<double> UMRTEMU_Index { get; set; }
        public Nullable<double> JNUE_Index { get; set; }
        public Nullable<double> CANLXEMR_Index { get; set; }
        public Nullable<double> GRUEPR_Index { get; set; }
        public Nullable<double> UKUEILOR_Index { get; set; }
        public Nullable<double> NEUENTTR_Index { get; set; }
        public Nullable<double> KOEAUERS_Index { get; set; }
        public Nullable<double> AULFUNEM_Index { get; set; }
        public Nullable<double> HPIMLEVL_Index { get; set; }
        public Nullable<double> GDP_CHWG_Index { get; set; }
        public Nullable<double> CGE9MP_Index { get; set; }
        public Nullable<double> EUGNEMU_Index { get; set; }
        public Nullable<double> GRGDEGDP_Index { get; set; }
        public Nullable<double> UKGRABMI_Index { get; set; }
        public Nullable<double> NEGDPESA_Index { get; set; }
        public Nullable<double> JGDPGDP_Index { get; set; }
        public Nullable<double> KOGDSTOT_Index { get; set; }
        public Nullable<double> AUNAGDP_Index { get; set; }
        public Nullable<double> EUQDGEUR_Index { get; set; }
        public Nullable<double> USCABAL_Index { get; set; }
        public Nullable<double> EHCAUS_Index { get; set; }
        public Nullable<double> GRCAEU_Index { get; set; }
        public Nullable<double> EHCADE_Index { get; set; }
        public Nullable<double> EUSATOTN_Index { get; set; }
        public Nullable<double> EUR003M_Index { get; set; }
        public Nullable<double> EUORDEPO_Index { get; set; }
        public Nullable<double> USDR1T_CMPN_Curncy { get; set; }
        public Nullable<double> FDTR_Index { get; set; }
        public Nullable<double> SXEE_Index { get; set; }
        public Nullable<double> NG1_Comdty { get; set; }
        public Nullable<double> CO1_COMDTY { get; set; }
        public Nullable<double> CL1_Comdty { get; set; }
        public Nullable<double> XOI_Index { get; set; }
        public Nullable<double> EURUSD_Curncy { get; set; }
        public Nullable<double> USDCNY_Curncy { get; set; }
        public Nullable<double> USDJPY_Curncy { get; set; }
        public Nullable<double> USDKRW_Curncy { get; set; }
        public Nullable<double> USDTWD_Curncy { get; set; }
        public Nullable<double> EURTWD_Curncy { get; set; }
        public Nullable<double> CNYTWD_Curncy { get; set; }
        public Nullable<double> JPYTWD_Curncy { get; set; }
        public Nullable<double> KRWTWD_Curncy { get; set; }
        public Nullable<double> EURR002W_Index { get; set; }
        public Nullable<double> NAPMPMI_Index { get; set; }
        public Nullable<double> NAPMNMI_Index { get; set; }
        public Nullable<double> NAPMNEWO_Index { get; set; }
        public Nullable<double> OUTFGAF_Index { get; set; }
        public Nullable<double> LEI_WKIJ_Index { get; set; }
        public Nullable<double> LEI_LCI_Index { get; set; }
        public Nullable<double> USHBMIDX_Index { get; set; }
        public Nullable<double> ARDIMONY_Index { get; set; }
        public Nullable<double> M1_Index { get; set; }
        public Nullable<double> ECMAM1_Index { get; set; }
        public Nullable<double> M2_Index { get; set; }
        public Nullable<double> ECMAM2_Index { get; set; }
        public Nullable<double> CEEREU_Index { get; set; }
        public Nullable<double> DXY_Curncy { get; set; }
        public Nullable<double> EUBCI_Index { get; set; }
        public Nullable<double> OEDEA044_Index { get; set; }
        public Nullable<double> EUESEMU_Index { get; set; }
        public Nullable<double> SNTEEUGX_Index { get; set; }
        public Nullable<double> XTSBEZ_Index { get; set; }
        public Nullable<double> GRTBALE_Index { get; set; }
        public Nullable<double> EBLS11NC_Index { get; set; }
        public Nullable<double> MXWO0MT_Index { get; set; }
        public Nullable<double> S5MATRX_Index { get; set; }
        public Nullable<double> XAU_Curncy { get; set; }
        public Nullable<double> USTBTOT_Index { get; set; }
        public Nullable<double> ADP_CHNG_Index { get; set; }
        public Nullable<double> NFP_TCH_Index { get; set; }
        public Nullable<double> CNSTTMOM_Index { get; set; }
        public Nullable<double> TMNOCHNG_Index { get; set; }
        public Nullable<double> DGNOCHNG_Index { get; set; }
        public Nullable<double> IP_CHNG_Index { get; set; }
        public Nullable<double> NHSPSTOT_Index { get; set; }
        public Nullable<double> NHCHSTCH_Index { get; set; }
        public Nullable<double> NHSPATOT_Index { get; set; }
        public Nullable<double> NHCHATCH_Index { get; set; }
        public Nullable<double> LEI_CHNG_Index { get; set; }
        public Nullable<double> ETSLTOTL_Index { get; set; }
        public Nullable<double> ETSLMOM_Index { get; set; }
        public Nullable<double> NHSLTOT_Index { get; set; }
        public Nullable<double> NHSLCHNG_Index { get; set; }
        public Nullable<double> CONSSENT_Index { get; set; }
        public Nullable<double> RSTAMOM_Index { get; set; }
        public Nullable<double> EUPPEMUM_Index { get; set; }
        public Nullable<double> EUCCEMU_Index { get; set; }
        public Nullable<double> CPMINDX_Index { get; set; }
        public Nullable<double> MPMICNMA_Index { get; set; }
        public Nullable<double> CNFRBAL_Index { get; set; }
        public Nullable<double> CNCPIYOY_Index { get; set; }
        public Nullable<double> CHEFTYOY_Index { get; set; }
        public Nullable<double> CNMS2YOY_Index { get; set; }
        public Nullable<double> CNFRIMPY_Index { get; set; }
        public Nullable<double> CNFREXPY_Index { get; set; }
        public Nullable<double> GRFIDEBT_Index { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    }
}
