//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flow_Info
    {
        public string PRJID { get; set; }
        public string FLOWID { get; set; }
        public string Group_Product_Code { get; set; }
        public System.DateTime Publish_Date { get; set; }
        public System.DateTime Apply_On_Date { get; set; }
        public Nullable<System.DateTime> Apply_Off_Date { get; set; }
        public string Issuer { get; set; }
        public string Memo { get; set; }
    
        public virtual Group_Product Group_Product { get; set; }
        public virtual IFRS9_User IFRS9_User { get; set; }
    }
}
