//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade_Moody_Info
    {
        public string Data_Year { get; set; }
        public string Rating { get; set; }
        public Nullable<int> PD_Grade { get; set; }
        public string Rating_Adjust { get; set; }
        public Nullable<int> Grade_Adjust { get; set; }
        public Nullable<double> Moodys_PD { get; set; }
        public string Status { get; set; }
        public string Auditor_Reply { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Audit_date { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    }
}
