//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_Main
    {
        public string Reference_Nbr { get; set; }
        public string Customer_Nbr { get; set; }
        public Nullable<double> Ead { get; set; }
        public Nullable<double> Principal { get; set; }
        public Nullable<double> Interest_Receivable { get; set; }
        public string Principal_Payment_Method_Code { get; set; }
        public Nullable<int> Total_Period { get; set; }
        public Nullable<double> Current_Int_Rate { get; set; }
        public Nullable<double> Current_Pd { get; set; }
        public Nullable<double> Current_Lgd { get; set; }
        public Nullable<int> Remaining_Month { get; set; }
        public Nullable<double> Eir { get; set; }
        public string CPD_Segment_Code { get; set; }
        public Nullable<System.DateTime> Processing_Date { get; set; }
        public string Product_Code { get; set; }
        public string Department { get; set; }
        public string PD_Model_Code { get; set; }
        public string Current_Rating_Code { get; set; }
        public System.DateTime Report_Date { get; set; }
        public Nullable<System.DateTime> Maturity_Date { get; set; }
        public string Account_Code { get; set; }
        public string BadCredit_Ind { get; set; }
        public string Charge_Off_Ind { get; set; }
        public string Collateral_Legal_Action_Ind { get; set; }
        public string Credit_Black_List_Ind { get; set; }
        public string Credit_Card_Block_code { get; set; }
        public string Credit_Review_Risk_Grade { get; set; }
        public string Current_External_Rating { get; set; }
        public string Current_External_Rating_1 { get; set; }
        public string Current_External_Rating_2 { get; set; }
        public string Current_External_Rating_3 { get; set; }
        public string Current_External_Rating_4 { get; set; }
        public string Current_External_Rating_On_Missing { get; set; }
        public string Current_Internal_Rating { get; set; }
        public string Default_Ind { get; set; }
        public Nullable<int> Delinquent_Days { get; set; }
        public string Early_Warning_Ind { get; set; }
        public string Five_Types_Delinquent_Category { get; set; }
        public string Ias39_Impaire_Ind { get; set; }
        public string Ias39_Impaire_Desc { get; set; }
        public string Industry_Average_Rating { get; set; }
        public string Manual_Identified_Impaire_Stage_Code { get; set; }
        public string Internal_Risk_Classification { get; set; }
        public Nullable<double> Off_Bs_Item_Paid_Amt { get; set; }
        public string Original_External_Rating { get; set; }
        public string Original_External_Rating_1 { get; set; }
        public string Original_External_Rating_2 { get; set; }
        public string Original_External_Rating_3 { get; set; }
        public string Original_External_Rating_4 { get; set; }
        public string Original_External_Rating_On_Missing { get; set; }
        public string Original_Internal_Rating { get; set; }
        public string Other_BadCredit_Ind { get; set; }
        public Nullable<int> Other_Lending_Max_Delinquent_Days { get; set; }
        public string Product_Average_Rating { get; set; }
        public string Restructure_Ind { get; set; }
        public string Ten_Types_Delinquent_Category { get; set; }
        public string Watch_List_Ind { get; set; }
        public string Write_Off_Ind { get; set; }
        public Nullable<int> Version { get; set; }
        public string Lien_position { get; set; }
        public Nullable<double> Ori_Amount { get; set; }
        public Nullable<int> Payment_Frequency { get; set; }
    }
}
