//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IFRS9_User()
        {
            this.IFRS9_Menu_Set = new HashSet<IFRS9_Menu_Set>();
            this.IFRS9_User_Log = new HashSet<IFRS9_User_Log>();
            this.IFRS9_Assessment_Config = new HashSet<IFRS9_Assessment_Config>();
            this.IFRS9_Assessment_Config1 = new HashSet<IFRS9_Assessment_Config>();
            this.Flow_Info = new HashSet<Flow_Info>();
        }
    
        public string User_Account { get; set; }
        public string User_Name { get; set; }
        public string User_Password { get; set; }
        public bool AdminFlag { get; set; }
        public bool Effective { get; set; }
        public bool LoginFlag { get; set; }
        public string DebtType { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_Menu_Set> IFRS9_Menu_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_User_Log> IFRS9_User_Log { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_Assessment_Config> IFRS9_Assessment_Config { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_Assessment_Config> IFRS9_Assessment_Config1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flow_Info> Flow_Info { get; set; }
    }
}
