//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_RE_EL
    {
        public int Id { get; set; }
        public System.DateTime Report_Date { get; set; }
        public string FLOWID { get; set; }
        public string Message { get; set; }
        public string Create_User { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.TimeSpan Create_Time { get; set; }
    }
}
