//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_Event_Log
    {
        public int Id { get; set; }
        public string User_Account { get; set; }
        public string Menu_Id { get; set; }
        public System.DateTime Login_Time { get; set; }
        public System.DateTime Browse_Time { get; set; }
        public string Action_Name { get; set; }
        public string Event_Name { get; set; }
        public System.DateTime Event_Begin { get; set; }
        public Nullable<System.DateTime> Event_Complete { get; set; }
        public Nullable<bool> Event_Flag { get; set; }
    
        public virtual IFRS9_Browse_Log IFRS9_Browse_Log { get; set; }
    }
}
