//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFRS9_Menu_Sub
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IFRS9_Menu_Sub()
        {
            this.IFRS9_Menu_Set = new HashSet<IFRS9_Menu_Set>();
            this.IFRS9_Browse_Log = new HashSet<IFRS9_Browse_Log>();
        }
    
        public string Menu { get; set; }
        public string Menu_Id { get; set; }
        public string Menu_Detail { get; set; }
        public string Class { get; set; }
        public string Href { get; set; }
        public int SortNum { get; set; }
        public string DebtType { get; set; }
        public string Create_User { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.TimeSpan> Create_Time { get; set; }
        public string LastUpdate_User { get; set; }
        public Nullable<System.DateTime> LastUpdate_Date { get; set; }
        public Nullable<System.TimeSpan> LastUpdate_Time { get; set; }
    
        public virtual IFRS9_Menu_Main IFRS9_Menu_Main { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_Menu_Set> IFRS9_Menu_Set { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IFRS9_Browse_Log> IFRS9_Browse_Log { get; set; }
    }
}
