//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IFRS9Entities : DbContext
    {
        public IFRS9Entities()
            : base("name=IFRS9Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Econ_Domestic> Econ_Domestic { get; set; }
        public virtual DbSet<Group_Product> Group_Product { get; set; }
        public virtual DbSet<IFRS9_Main> IFRS9_Main { get; set; }
        public virtual DbSet<IFRS9_Menu_Main> IFRS9_Menu_Main { get; set; }
        public virtual DbSet<IFRS9_Menu_Sub> IFRS9_Menu_Sub { get; set; }
        public virtual DbSet<Moody_Monthly_PD_Info> Moody_Monthly_PD_Info { get; set; }
        public virtual DbSet<Moody_Quartly_PD_Info> Moody_Quartly_PD_Info { get; set; }
        public virtual DbSet<Moody_Tm_YYYY> Moody_Tm_YYYY { get; set; }
        public virtual DbSet<Rating_Info> Rating_Info { get; set; }
        public virtual DbSet<Rating_Info_SampleInfo> Rating_Info_SampleInfo { get; set; }
        public virtual DbSet<Transfer_CheckTable> Transfer_CheckTable { get; set; }
        public virtual DbSet<Moody_Predit_PD_Info> Moody_Predit_PD_Info { get; set; }
        public virtual DbSet<Loan_IAS39_Info> Loan_IAS39_Info { get; set; }
        public virtual DbSet<Loan_Recovery_Info> Loan_Recovery_Info { get; set; }
        public virtual DbSet<IFRS9_Menu_Set> IFRS9_Menu_Set { get; set; }
        public virtual DbSet<Bond_Category_Info> Bond_Category_Info { get; set; }
        public virtual DbSet<Bond_Ticker_Info> Bond_Ticker_Info { get; set; }
        public virtual DbSet<Flow_Info> Flow_Info { get; set; }
        public virtual DbSet<Fixed_Income_CEIC_Info> Fixed_Income_CEIC_Info { get; set; }
        public virtual DbSet<Fixed_Income_Moody_Info> Fixed_Income_Moody_Info { get; set; }
        public virtual DbSet<Gov_Info_Monthly> Gov_Info_Monthly { get; set; }
        public virtual DbSet<Gov_Info_Quartly> Gov_Info_Quartly { get; set; }
        public virtual DbSet<Gov_Info_Yearly> Gov_Info_Yearly { get; set; }
        public virtual DbSet<Bond_Qualitative_Assessment_Result_File> Bond_Qualitative_Assessment_Result_File { get; set; }
        public virtual DbSet<Guarantor_Ticker> Guarantor_Ticker { get; set; }
        public virtual DbSet<Issuer_Ticker> Issuer_Ticker { get; set; }
        public virtual DbSet<Econ_D_YYYYMMDD> Econ_D_YYYYMMDD { get; set; }
        public virtual DbSet<EL_Data_Out> EL_Data_Out { get; set; }
        public virtual DbSet<Group_Product_Code_Mapping> Group_Product_Code_Mapping { get; set; }
        public virtual DbSet<Rating_History> Rating_History { get; set; }
        public virtual DbSet<Bond_Rating> Bond_Rating { get; set; }
        public virtual DbSet<Guarantor_Rating> Guarantor_Rating { get; set; }
        public virtual DbSet<Issuer_Rating> Issuer_Rating { get; set; }
        public virtual DbSet<EL_Data_In> EL_Data_In { get; set; }
        public virtual DbSet<Flow_Apply_Status> Flow_Apply_Status { get; set; }
        public virtual DbSet<SMF_Info> SMF_Info { get; set; }
        public virtual DbSet<IFRS9_Log> IFRS9_Log { get; set; }
        public virtual DbSet<IFRS9_EL> IFRS9_EL { get; set; }
        public virtual DbSet<SMF_Group> SMF_Group { get; set; }
        public virtual DbSet<Bond_Rating_Warning> Bond_Rating_Warning { get; set; }
        public virtual DbSet<Bond_ISIN_Changed_Info> Bond_ISIN_Changed_Info { get; set; }
        public virtual DbSet<Bond_Rating_Info> Bond_Rating_Info { get; set; }
        public virtual DbSet<Bond_Rating_Summary> Bond_Rating_Summary { get; set; }
        public virtual DbSet<Risk_Parm> Risk_Parm { get; set; }
        public virtual DbSet<Gov_Info_Ticker> Gov_Info_Ticker { get; set; }
        public virtual DbSet<IFRS9_Browse_Log> IFRS9_Browse_Log { get; set; }
        public virtual DbSet<IFRS9_User_Log> IFRS9_User_Log { get; set; }
        public virtual DbSet<IFRS9_Event_Log> IFRS9_Event_Log { get; set; }
        public virtual DbSet<Basic_Assessment_Parm> Basic_Assessment_Parm { get; set; }
        public virtual DbSet<IFRS9_User> IFRS9_User { get; set; }
        public virtual DbSet<Treasury_Securities_Info> Treasury_Securities_Info { get; set; }
        public virtual DbSet<EL_Data_In_Update> EL_Data_In_Update { get; set; }
        public virtual DbSet<Warning_List_Parm> Warning_List_Parm { get; set; }
        public virtual DbSet<Watching_List_Parm> Watching_List_Parm { get; set; }
        public virtual DbSet<IFRS9_Assessment> IFRS9_Assessment { get; set; }
        public virtual DbSet<IFRS9_Assessment_Config> IFRS9_Assessment_Config { get; set; }
        public virtual DbSet<IFRS9_Loan_Report> IFRS9_Loan_Report { get; set; }
        public virtual DbSet<Bond_Basic_Assessment> Bond_Basic_Assessment { get; set; }
        public virtual DbSet<Bond_Spread_Info> Bond_Spread_Info { get; set; }
        public virtual DbSet<Bond_Rating_Parm> Bond_Rating_Parm { get; set; }
        public virtual DbSet<Loan_Stage_Setting> Loan_Stage_Setting { get; set; }
        public virtual DbSet<Econ_D_Var> Econ_D_Var { get; set; }
        public virtual DbSet<Assessment_Sub_Kind_Ticker> Assessment_Sub_Kind_Ticker { get; set; }
        public virtual DbSet<Rating_Update_Info> Rating_Update_Info { get; set; }
        public virtual DbSet<Econ_F_YYYYMMDD> Econ_F_YYYYMMDD { get; set; }
        public virtual DbSet<Scheduling_Report> Scheduling_Report { get; set; }
        public virtual DbSet<Bond_Qualitative_Assessment> Bond_Qualitative_Assessment { get; set; }
        public virtual DbSet<Bond_Qualitative_Assessment_Result> Bond_Qualitative_Assessment_Result { get; set; }
        public virtual DbSet<Bond_Quantitative_Result_File> Bond_Quantitative_Result_File { get; set; }
        public virtual DbSet<Bond_Quantitative_Result> Bond_Quantitative_Result { get; set; }
        public virtual DbSet<Bond_Quantitative_Resource> Bond_Quantitative_Resource { get; set; }
        public virtual DbSet<Bond_Accounting_EL> Bond_Accounting_EL { get; set; }
        public virtual DbSet<Moody_LGD_Info> Moody_LGD_Info { get; set; }
        public virtual DbSet<IFRS9_Foward_Looking_Parm> IFRS9_Foward_Looking_Parm { get; set; }
        public virtual DbSet<Grade_Mapping_Info> Grade_Mapping_Info { get; set; }
        public virtual DbSet<Grade_Moody_Info> Grade_Moody_Info { get; set; }
        public virtual DbSet<Bond_Spread_Trade_Info> Bond_Spread_Trade_Info { get; set; }
        public virtual DbSet<Fixed_Income_AbuDhabi_Info> Fixed_Income_AbuDhabi_Info { get; set; }
        public virtual DbSet<Notice_Info> Notice_Info { get; set; }
        public virtual DbSet<Mail_Info> Mail_Info { get; set; }
        public virtual DbSet<Bond_Account_Info> Bond_Account_Info { get; set; }
        public virtual DbSet<Loan_Account_Info> Loan_Account_Info { get; set; }
        public virtual DbSet<Loan_Report_Info> Loan_Report_Info { get; set; }
        public virtual DbSet<Bond_Assessment_Parm> Bond_Assessment_Parm { get; set; }
        public virtual DbSet<IFRS9_RE_EL> IFRS9_RE_EL { get; set; }
    }
}
