//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_IAS39_Info
    {
        public string Reference_Nbr { get; set; }
        public string Mdr_Month { get; set; }
        public double EIR { get; set; }
        public string NO34RCV { get; set; }
        public string IAS39_Impaire_Ind { get; set; }
        public string IAS39_Impaire_Desc { get; set; }
        public double Principal { get; set; }
        public double Interest_Receivable { get; set; }
        public Nullable<System.DateTime> Processing_Date { get; set; }
        public System.DateTime Report_Date { get; set; }
    }
}
