//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Recovery_Info
    {
        public string Data_Year { get; set; }
        public string NO34RCV { get; set; }
        public double Recovery_Rate_1 { get; set; }
        public double Recovery_Rate_2 { get; set; }
        public double Recovery_Rate_3 { get; set; }
        public double Recovery_Rate_4 { get; set; }
        public double Recovery_Rate_5 { get; set; }
        public double Recovery_Rate_6 { get; set; }
        public double Recovery_Rate_7 { get; set; }
        public double Recovery_Rate_8 { get; set; }
        public double Recovery_Rate_9 { get; set; }
        public double Recovery_Rate_10 { get; set; }
        public double Recovery_Rate_11 { get; set; }
        public double Recovery_Rate_12 { get; set; }
        public double Recovery_Rate_13 { get; set; }
        public double Recovery_Rate_14 { get; set; }
        public double Recovery_Rate_15 { get; set; }
        public double Recovery_Rate_16 { get; set; }
        public double Recovery_Rate_17 { get; set; }
        public double Recovery_Rate_18 { get; set; }
        public double Recovery_Rate_19 { get; set; }
        public double Recovery_Rate_20 { get; set; }
    }
}
