//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moody_Tm_YYYY
    {
        public int Id { get; set; }
        public string From_To { get; set; }
        public Nullable<double> Aaa { get; set; }
        public Nullable<double> Aa1 { get; set; }
        public Nullable<double> Aa2 { get; set; }
        public Nullable<double> Aa3 { get; set; }
        public Nullable<double> A1 { get; set; }
        public Nullable<double> A2 { get; set; }
        public Nullable<double> A3 { get; set; }
        public Nullable<double> Baa1 { get; set; }
        public Nullable<double> Baa2 { get; set; }
        public Nullable<double> Baa3 { get; set; }
        public Nullable<double> Ba1 { get; set; }
        public Nullable<double> Ba2 { get; set; }
        public Nullable<double> Ba3 { get; set; }
        public Nullable<double> B1 { get; set; }
        public Nullable<double> B2 { get; set; }
        public Nullable<double> B3 { get; set; }
        public Nullable<double> Caa1 { get; set; }
        public Nullable<double> Caa2 { get; set; }
        public Nullable<double> Caa3 { get; set; }
        public Nullable<double> Ca_C { get; set; }
        public Nullable<double> WR { get; set; }
        public Nullable<double> Default_Value { get; set; }
    }
}
