//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moody_LGD_Info
    {
        public string Data_Year { get; set; }
        public string Lien_Position { get; set; }
        public Nullable<double> Recovery_Rate { get; set; }
        public Nullable<double> LGD { get; set; }
        public string Status { get; set; }
        public string Auditor_Reply { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Audit_date { get; set; }
    }
}
