//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Moody_Predit_PD_Info
    {
        public int Id { get; set; }
        public string Data_Year { get; set; }
        public string Period { get; set; }
        public string PD_TYPE { get; set; }
        public Nullable<double> PD { get; set; }
    }
}
