//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating_Info
    {
        public int Record_ID { get; set; }
        public string Bond_Number { get; set; }
        public Nullable<System.DateTime> Rating_Date { get; set; }
        public string Rating_Object { get; set; }
        public string Rating { get; set; }
        public string RTG_Bloomberg_Field { get; set; }
        public System.DateTime Report_Date { get; set; }
        public string Rating_Org { get; set; }
    }
}
