//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduling_Report
    {
        public int ID { get; set; }
        public string Scheduling_Type { get; set; }
        public string Content_memo { get; set; }
        public Nullable<System.DateTime> Report_Date { get; set; }
        public Nullable<int> Version { get; set; }
        public string File_Name { get; set; }
        public string File_path { get; set; }
        public System.DateTime Create_Date { get; set; }
        public string Delete_YN { get; set; }
        public Nullable<System.DateTime> Delete_Date { get; set; }
        public string Processing_User { get; set; }
    }
}
