//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMF_Info
    {
        public string SMF_Code { get; set; }
        public string SMF { get; set; }
        public string SMF_Desc { get; set; }
        public string Asset_type_Code { get; set; }
        public string Asset_Type { get; set; }
    }
}
