//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transfer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Warning_List_Parm
    {
        public int Rule_ID { get; set; }
        public string Basic_Pass_Check_Point { get; set; }
        public string Basic_Pass { get; set; }
        public string Rating_Check_Point { get; set; }
        public string Rating_Threshold { get; set; }
        public string Data_Year { get; set; }
        public Nullable<int> Rating_Threshold_Map_Grade { get; set; }
        public Nullable<int> Rating_Threshold_Map_Grade_Adjust { get; set; }
        public string Including_Ind_0 { get; set; }
        public string Apply_Range_0 { get; set; }
        public string Rating_from { get; set; }
        public Nullable<int> Rating_from_Map_Grade { get; set; }
        public Nullable<int> Rating_from_Map_Grade_Adjust { get; set; }
        public string Rating_To { get; set; }
        public Nullable<int> Rating_To_Map_Grade { get; set; }
        public Nullable<int> Rating_To_Map_Grade_Adjust { get; set; }
        public Nullable<int> Value_Change_Months { get; set; }
        public string Including_Ind_1 { get; set; }
        public string Apply_Range_1 { get; set; }
        public string Rule_setter { get; set; }
        public System.DateTime Rule_setting_Date { get; set; }
        public string Auditor { get; set; }
        public Nullable<System.DateTime> Audit_Date { get; set; }
        public string Status { get; set; }
        public string Rule_desc { get; set; }
        public Nullable<int> Spread_Change_Months { get; set; }
        public string Including_Ind_2 { get; set; }
        public string Apply_Range_2 { get; set; }
        public string IsActive { get; set; }
    }
}
